name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Ручной запуск

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(f'Python {sys.version}')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl numpy pyinstaller

    - name: Verify files
      run: |
        dir
        echo "Checking Python files:"
        python -c "import pandas; print('pandas OK')"
        python -c "import openpyxl; print('openpyxl OK')"
        python -c "import numpy; print('numpy OK')"

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --console --name "ProductionPlanner" production_planner.py

    - name: Test executable
      run: |
        echo "Testing the executable..."
        cd dist
        dir
        echo "Executable built successfully!"

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ProductionPlanner-Windows
        path: dist/ProductionPlanner.exe
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ProductionPlanner.exe
        body: "Windows executable for Production Planner"
