name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl numpy pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --console --name "ProductionPlanner" production_planner.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ProductionPlanner-Windows
        path: dist/ProductionPlanner.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ProductionPlanner.exe
